"""
CORREGIR: Template account.document_tax_totals_copy_3
Agregar validación t-if para evitar error cuando tax_totals es False
"""
import xmlrpc.client

# Configuración
url = 'https://riofuturo.server98c6e.oerpondemand.net'
db = 'riofuturo-master'
username = 'mvalladares@riofuturo.cl'
password = 'c0766224bec30cac071ffe43a858c9ccbd521ddd'

# Conectar
common = xmlrpc.client.ServerProxy(f'{url}/xmlrpc/2/common')
uid = common.authenticate(db, username, password, {})
models = xmlrpc.client.ServerProxy(f'{url}/xmlrpc/2/object')

print("=" * 100)
print("CORREGIR TEMPLATE: account.document_tax_totals_copy_3")
print("=" * 100)

# ID del template con error
TEMPLATE_ID = 4696

# Nuevo arch_db corregido con validación t-if
arch_corregido = '''<t t-name="account.document_tax_totals_copy_3">
    <!--
        Generic template to display tax totals in pdf reports.
        Used by invoices, SO and PO.

        ARGUMENTS:
        - tax_totals: dict in the form generated by account.move's _get_tax_totals.
    -->
    <t t-if="tax_totals">
        <t t-foreach="tax_totals['subtotals']" t-as="subtotal">
            <tr class="border-black o_subtotal">
                <td><strong t-esc="subtotal['name']"/></td>

                <td class="text-end">
                    <span t-att-class="oe_subtotal_footer_separator" t-esc="subtotal['formatted_amount']"/>
                </td>
            </tr>

            <t t-set="subtotal_to_show" t-value="subtotal['name']"/>
            <t t-call="account.tax_groups_totals_copy_3"/>
        </t>

        <!--Total amount with all taxes-->
        <tr class="border-black o_total">
            <td><strong>Total</strong></td>
            <td class="text-end">
                <span t-esc="tax_totals['formatted_amount_total']"/>
            </td>
        </tr>
    </t>
</t>'''

# Aplicar corrección
print("\n🔧 Aplicando corrección...")

try:
    result = models.execute_kw(db, uid, password,
        'ir.ui.view', 'write',
        [[TEMPLATE_ID], {'arch_db': arch_corregido}]
    )
    
    if result:
        print(f"✅ Template ID {TEMPLATE_ID} corregido exitosamente")
    else:
        print(f"❌ No se pudo actualizar el template")
        
except Exception as e:
    print(f"❌ Error: {e}")


# ============================================================
# Corregir también las copias del template que tengan el mismo problema
# ============================================================
print("\n" + "-" * 80)
print("CORRIGIENDO COPIAS ADICIONALES DEL TEMPLATE")
print("-" * 80)

# IDs de las copias que también pueden tener el problema
template_copies = [
    (4726, 'account.document_tax_totals_copy_3_copy_1'),
    (4733, 'account.document_tax_totals_copy_3_copy_2'),
    (4991, 'account.document_tax_totals_copy_3_copy_3'),
]

for template_id, template_key in template_copies:
    # Obtener el arch actual
    template = models.execute_kw(db, uid, password,
        'ir.ui.view', 'read',
        [[template_id]],
        {'fields': ['arch_db']}
    )
    
    if template:
        arch = template[0]['arch_db']
        
        # Verificar si necesita corrección
        if 't-foreach="tax_totals' in arch and 't-if="tax_totals"' not in arch:
            print(f"\n⚠️  Template {template_id} ({template_key}) necesita corrección")
            
            # Crear versión corregida con el nombre correcto
            arch_corregido_copy = arch.replace(
                '<t t-foreach="tax_totals[',
                '<t t-if="tax_totals">\n        <t t-foreach="tax_totals['
            )
            
            # Agregar cierre del t-if antes del cierre final
            if '</t>' in arch_corregido_copy:
                # Insertar </t> de cierre para el t-if antes del último </t>
                last_close = arch_corregido_copy.rfind('</t>')
                arch_corregido_copy = arch_corregido_copy[:last_close] + '    </t>\n' + arch_corregido_copy[last_close:]
            
            try:
                result = models.execute_kw(db, uid, password,
                    'ir.ui.view', 'write',
                    [[template_id], {'arch_db': arch_corregido_copy}]
                )
                if result:
                    print(f"   ✅ Corregido: {template_key}")
            except Exception as e:
                print(f"   ❌ Error: {e}")
        else:
            print(f"✅ Template {template_id} ya tiene validación o no la necesita")


# ============================================================
# Verificación final
# ============================================================
print("\n" + "=" * 100)
print("VERIFICACIÓN")
print("=" * 100)

# Leer el template corregido
verificar = models.execute_kw(db, uid, password,
    'ir.ui.view', 'read',
    [[TEMPLATE_ID]],
    {'fields': ['arch_db']}
)

if verificar and 't-if="tax_totals"' in verificar[0]['arch_db']:
    print("\n✅ Template principal corregido correctamente")
    print("   Ahora incluye: <t t-if=\"tax_totals\">")
else:
    print("\n⚠️  Verificar manualmente el template")

print("\n🎉 CORRECCIÓN COMPLETADA")
print("   Intenta previsualizar el PDF nuevamente")
